### ISSUE TITLE
Something about Windows Vista

### ISSUE THREAD

**Issue by MSLoverMS** [UMSKT/UMSKT#100]
Hello everyone!
I found a website that can generate SLIC binary files for OEM activation:  https://d-fault.nl/sliccreator
I haven't tested myself but looks promising!
Bye!

**Comment by thepwrtank18** [comment]
Vista and up is a big gray area, since for what we know, the same product key system for Vista is the same system for Windows 11. XP's a lost cause for MS, since it's more than 20 years old at this point, but Vista still has modern stuff inside.

**Comment by MSLoverMS** [comment]
OK, sorry!

**Comment by WitherOrNot** [comment]
We have somewhat researched Vista already, but didn't find many promising directions that align with the mission of this particular project.

**Comment by MSLoverMS** [comment]
OK, I'm sorry!

**Comment by MSLoverMS** [comment]
Thank you everyone for doing this project!
