### ISSUE TITLE
[Feature sugerence] mod7-based algorithm key generation

### ISSUE THREAD

**Issue by MSLoverMS** [UMSKT/UMSKT#101]
Sorry for being so asky!

Is it planned to include mod7 algorithm product key generation?
More info here: https://gurney.dev/posts/mod7/

It would be useful for:
- Windows 95
- Windows NT 4.0
- Office 95
- Office 97

Thank you for your dedication.

**Comment by Neo-Desktop** [comment]
it is currently implemented in the refactor branch and will be generally available once it's finalized

**Comment by MSLoverMS** [comment]
@Neo-Desktop OK, many thanks!
