### ISSUE TITLE
Office 2010 support

### ISSUE THREAD

**Issue by Lindsay-Naegle** [UMSKT/UMSKT#104]
Hello everyone!
I've just discovered that Office 2010 is the only version of Microsoft Office that cannot be activated permanently as neither you nor MAS support this product. 

- **Office 2000 and earlier:** No activation needed
- **Office XP to Office 2007:**  CID from UMSKT
- **Office 2010:**  X
- **Office 2013 to 2024:** Ohook from MAS
- **Office 365:** Ohook from MAS

Do you have plans to support this product?

Thank You.

**Comment by thecatontheceiling** [comment]
https://massgrave.dev/unsupported_products_activation#office-2010-vl-on-windows-xp--vista

**Comment by thepwrtank18** [comment]
Office 2010 is in the area where it's using modern-day license keys (so we can't touch it without being put in the Microsoft AI Copilot Electric Chair:tm:), but not new enough to support Ohook.
