### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by Coolgaming-2011** [UMSKT/UMSKT#107]
`CMake Error at /data/data/com.termux/files/usr/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
  version "3.3.2")
Call Stack (most recent call first):
  /data/data/com.termux/files/usr/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:603 (_FPHSA_FAILURE_MESSAGE)
  /data/data/com.termux/files/usr/share/cmake-3.30/Modules/FindOpenSSL.cmake:689 (find_package_handle_standard_args)
  CMakeLists.txt:102 (FIND_PACKAGE)`

**Comment by techguy16** [comment]
Can you try compiling it on a computer? This will determine whether it is an issue with the source or Termux.

**Comment by Coolgaming-2011** [comment]
> Can you try compiling it on a computer? This will determine whether it is an issue with the source or Termux.

I will try it soon

**Comment by Coolgaming-2011** [comment]
> Building on termux proceeds with setting `-DUMSKT_USE_SHARED_OPENSSL=on` - I guess it doesn't support static linking openssl?
> 
> That said, linking fails, apparently std::filesystem may not be present there?
> 
> ```
> /data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/bin/ld: DWARF error: could not find variable specification at offset 54
> /data/data/com.termux/files/usr/bin/ld: DWARF error: could not find variable specification at offset a10f
> CMakeFiles/umskt.dir/src/cli.cpp.o: in function `std::__ndk1::__fs::filesystem::exists(std::__ndk1::__fs::filesystem::path const&)':
> /data/data/com.termux/files/usr/include/c++/v1/filesystem:1615: undefined reference to `std::__ndk1::__fs::filesystem::__status(std::__ndk1::__fs::filesystem::path const&, std::__ndk1::error_code*)'
> /data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/include/c++/v1/filesystem:1615: undefined reference to `std::__ndk1::__fs::filesystem::__status(std::__ndk1::__fs::filesystem::path const&, std::__ndk1::error_code*)'
> ```



> Building on termux proceeds with setting `-DUMSKT_USE_SHARED_OPENSSL=on` - I guess it doesn't support static linking openssl?
> 
> That said, linking fails, apparently std::filesystem may not be present there?
> 
> ```
> /data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/bin/ld: DWARF error: could not find variable specification at offset 54
> /data/data/com.termux/files/usr/bin/ld: DWARF error: could not find variable specification at offset a10f
> CMakeFiles/umskt.dir/src/cli.cpp.o: in function `std::__ndk1::__fs::filesystem::exists(std::__ndk1::__fs::filesystem::path const&)':
> /data/data/com.termux/files/usr/include/c++/v1/filesystem:1615: undefined reference to `std::__ndk1::__fs::filesystem::__status(std::__ndk1::__fs::filesystem::path const&, std::__ndk1::error_code*)'
> /data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/include/c++/v1/filesystem:1615: undefined reference to `std::__ndk1::__fs::filesystem::__status(std::__ndk1::__fs::filesystem::path const&, std::__ndk1::error_code*)'
> ```

It works for me
