### ISSUE TITLE
add suport for serial and activation: Windows Plus! Media edition XP

### ISSUE THREAD

**Issue by www2000** [UMSKT/UMSKT#16]
I wand to request that we add support for generate "Windows Plus! Media edition" keys and activation?

**Comment by Neo-Desktop** [comment]
We will be looking into this

**Comment by Neo-Desktop** [comment]
BINK IDs 08 and 09 for license keys already in `keys.json` I'll add the product string right now

**Comment by pottzman** [comment]
Microsoft PLus! Media Center Edition does not use BINK ID08 or 09. it uses BINK ID 52 and 53 and Product ID must be XXXXX-140-XXXXXXX-XXXXX

**Comment by Neo-Desktop** [comment]
Ah, I was looking at the wrong PIDGen -

This appears to be the one you want: https://archive.org/details/msplus-dme

I was looking at was here: https://archive.org/download/microsoft-plus-xp

**Comment by Neo-Desktop** [comment]
We have 52 and 53 calculated but we cannot make keys with this version of the algorithm at this time.

Activation is still far away at this time, more research is needed to make a key extractor that works consistently

**Comment by www2000** [comment]
That oke for me and i think an other software/game that use BINK2002 is Microsoft Flight Simulator X that is release in 2006

**Comment by www2000** [comment]
I have current problems with the activation.
An  "Unknown installation ID version" error
the keys that i use:
licens key: M62BT-T63TQ-Q6YJV-F73XD-FB6BB
install id: 274754-839910-757671-263394-732034-857201-881993-965111-70

**Comment by Neo-Desktop** [comment]
We are currently working on this in chat, we've managed to factor activation for several products at this point, but its an individual process

**Comment by thepwrtank18** [comment]
![image](https://github.com/Neo-Desktop/WindowsXPKg/assets/57580668/f5072f12-8199-4812-8c4b-b30939aadaab)

**Comment by WitherOrNot** [comment]
can we close this issue?

**Comment by thepwrtank18** [comment]
> can we close this issue?

I suggest to wait until it's actually implemented in the git repo

**Comment by thepwrtank18** [comment]
so far, it's half-implemented (serial, not activation yet)

**Comment by WitherOrNot** [comment]
support has been implemented

**Comment by thepwrtank18** [comment]
![image](https://github.com/UMSKT/UMSKT/assets/57580668/1491d850-2a61-4f47-b671-6d5b2ad4e156)
almost 3 months

**Comment by www2000** [comment]
Better late than never
