### ISSUE TITLE
Proposal for alternate crypto backends, e.g. libsodium or libnettle?

### ISSUE THREAD

**Issue by TheGentleChainsaw** [UMSKT/UMSKT#21]
I know this might be a huge amount of work depending on how much of the OpenSSL library the program currently uses, and arguably not worth it for such a niche piece of software, but it would certainly be nice to have options at least. Libsodium in particular might also be good for making static builds smaller, once those are working again.

**Comment by Neo-Desktop** [comment]
While I'm not familiar with those libraries, as long as they have support for what we're trying to accomplish, I think it's absolutely worth looking into

Thanks for the tip, I'll bring it up in our development chat
