### ISSUE TITLE
Add Dockerfile for easy compilation

### ISSUE THREAD

**Issue by brakmic** [UMSKT/UMSKT#29]
Hi,

Here's a Dockerfile I'm using to compile and run `xpkey`. It runs Alpine Linux.

```dockerfile
# Stage 1: Builder
FROM alpine:3.18 as builder

# Install build dependencies
RUN apk add --no-cache \
  bash \
  build-base \
  git \
  cmake \
  openssl1.1-compat \
  openssl1.1-compat-dev \
  openssl1.1-compat-libs-static

WORKDIR /src

# Clone xpkey repository and build it
RUN git clone https://github.com/UMSKT/UMSKT.git . \
  && cd ./build \
  && cmake .. \
  && make

# Stage 2: Runner
FROM alpine:3.18 as runner

ENV HOME /root

# Copy xpkey binary & keys.json from builder
COPY --from=builder /src/build/xpkey /root/xpkey
COPY --from=builder /src/keys.json /root/keys.json

# Install bash
RUN apk add --no-cache bash

CMD ["bash"]

```
![Screenshot 2023-06-17 at 22 05 54](https://github.com/UMSKT/UMSKT/assets/56779/284a64a8-a2e8-405d-8b96-02710fdd2511)

Maybe it could be of some help to others. 

Many thanks to those who coded this fine piece of software.

**Comment by Neo-Desktop** [comment]
This Dockerfile is great! I think it would be a good idea to include it in the repository

**Comment by thepwrtank18** [comment]
+1

**Comment by brakmic** [comment]
> This Dockerfile is great! I think it would be a good idea to include it in the repository
> 
> the only thing I would update is using a newer version of openssl if possible
> 
> i.e. [openssl-dev](https://pkgs.alpinelinux.org/package/edge/main/x86_64/openssl-dev) and [openssl-libs-static](https://pkgs.alpinelinux.org/package/edge/main/x86_64/openssl-libs-static)

I tried it with OpenSSL 3.1, but CMake didn't accept it. However, it could still have been an error on my part. I'm not sure.

![Screenshot 2023-06-17 at 22 46 37](https://github.com/UMSKT/UMSKT/assets/56779/0476dcba-0e77-4851-b94c-42c86e2bb804)

**Comment by Neo-Desktop** [comment]
> > This Dockerfile is great! I think it would be a good idea to include it in the repository
> > the only thing I would update is using a newer version of openssl if possible
> > i.e. [openssl-dev](https://pkgs.alpinelinux.org/package/edge/main/x86_64/openssl-dev) and [openssl-libs-static](https://pkgs.alpinelinux.org/package/edge/main/x86_64/openssl-libs-static)
> 
> I tried it with OpenSSL 3.1, but CMake didn't accept it. However, it could still have been an error on my part. I'm not sure.
> 
> ![Screenshot 2023-06-17 at 22 46 37](https://user-images.githubusercontent.com/56779/246630922-0476dcba-0e77-4851-b94c-42c86e2bb804.png)

Interesting findings - thank you for trying that

I think this is something we should look into as CMake is able to properly detect `OpenSSL 3.0.2`

**Comment by brakmic** [comment]
I forgot to add example commands for building and running images. Sorry.

To build image: `docker build -t your/tagname .`

To run image: `docker run --rm -it --network=host --workdir /root your/tagname`

**Comment by Neo-Desktop** [comment]
so this dockerfile works well for me:
I'll close this issue when it's in master

```dockerfile
# Stage 1: Install Prerequisites
FROM alpine:latest as prerequisites 

# Install build dependencies
RUN apk add --no-cache \
  bash \
  build-base \
  git \
  cmake \
  openssl-dev \
  openssl-libs-static


# Stage 2: Build
FROM prerequisites as builder

WORKDIR /src
COPY . /src

# Build UMSKT from the local directory
RUN mkdir /src/build \
  && cd /src/build \
  && cmake .. \
  && make

# Stage 3: Runtime Environement
FROM alpine:latest as runner

ENV HOME /root
WORKDIR /root

# Copy xpkey binary & keys.json from builder
COPY --from=builder /src/build/xpkey /root/xpkey
COPY --from=builder /src/keys.json /root/keys.json

# Install bash
RUN apk add --no-cache bash

CMD ["bash"]

```

**Comment by Neo-Desktop** [comment]
Thank you for your contribution!
