### ISSUE TITLE
Check for the keys file in the same directory as xpkey

### ISSUE THREAD

**Issue by TheGentleChainsaw** [UMSKT/UMSKT#32]
Suggesting a small usability feature: If `-f <keysfile>` is not specified and `keys.json` is not in the shell's current directory, it should instead check for `keys.json` in the directory where the `xpkey` executable is kept.

**Comment by Neo-Desktop** [comment]
this is a great usability feature

in the future we are planning that `keys.json` will be compiled in, so hopefully this will be less of an issue at that point
