### ISSUE TITLE
Support for generating and activating XP Tablet PC / XP Media center

### ISSUE THREAD

**Issue by kcomputergeek** [UMSKT/UMSKT#34]
Is Support for generating and activating XP Tablet PC / XP Media center being looked into?

**Comment by Neo-Desktop** [comment]
yes at this point we have confirmed license key generation for almost all XP era products - activation for all XP products should just work

currently we're working on consolidating the various parameters for each individual product into a more sophisticated `keys.json` implementation

**Comment by WitherOrNot** [comment]
XP MCE uses XP Professional BINKs, with different product IDs. Automatic product ID generation is under #15
