### ISSUE TITLE
Python library

### ISSUE THREAD

**Issue by techguy16** [UMSKT/UMSKT#37]
I think I opened this on @Endermanch's XPKeygen, but I would really like for a universal python library (my [keygenlib](https://github.com/techguy16/keygenlib/) library). I have got a Product ID generator working, and a 1-in-20 keygen for XP working, but I don't understand ECC and stuff.

**Comment by WitherOrNot** [comment]
The activation algorithms have been implemented in SageMath (a variant of Python) below:

https://gist.github.com/WitherOrNot/455c922849aed6cb330eb9d5d656005c

https://gist.github.com/WitherOrNot/e2f1f4a6b17a7ffcd7e2426c75bc2278

https://gist.github.com/WitherOrNot/80f978c018f4157ecd079e9cb26269b3

**Comment by techguy16** [comment]
They use `hashlib`, which is included in Python. They'll need a bit of modification for running as 1 .py file, but thanks!

**Comment by Neo-Desktop** [comment]
I will close this issue as the intention of this project is to provide a c++ library.

the UMSKT project as a whole may provide a python port/library in the future

**Comment by techguy16** [comment]
@Neo-Desktop my python library can become the official UMSKT python library if you want.

**Comment by Neo-Desktop** [comment]
> @Neo-Desktop my python library can become the official UMSKT python library if you want.

so I brought this up in the developer's chat and this is a generous offer

we're currently in the process of a major refactor of the project (completely ditching openssl for crypto++)
https://github.com/UMSKT/UMSKT/tree/overhaul-2023-06-25

as it stands any official libraries and ports will need to mirror the API as best as possible

I think we'll be in a better place to revisit it once the refactor is finalized

**Comment by WitherOrNot** [comment]
Feel free to join the Zulip chat in the README to keep up with development updates

**Comment by techguy16** [comment]
@Neo-Desktop OK.

@WitherOrNot can I implement your code into keygenlib and modify it as long as I credit you?

**Comment by WitherOrNot** [comment]
sure!

**Comment by techguy16** [comment]
I've been trying to make the SageMath code work (sits there for an hour doing nothing on a PC that takes 1 second uaing UMSKT) and I think it will be easier if I just made some sort of library that connects to the UMSKT executable using `subprocess`. Is this OK?
