### ISSUE TITLE
How do i build this?

### ISSUE THREAD

**Issue by SuperVitu64** [UMSKT/UMSKT#39]
How do i build this? The guide says i gotta build it but i don't know what to use + how to build it. Sorry, i have neevr done this before.

**Comment by WitherOrNot** [comment]
We are currently refactoring. For now, you can download from the Actions links given in the README.

**Comment by SuperVitu64** [comment]
Sorry, i don't understand what you mean, could you link those action links on here or something?

**Comment by thepwrtank18** [comment]
> * *(GitHub account required)*
    * Download the latest experimental version using the Actions tab ([Windows](../../actions/workflows/windows.yml?query=branch%3Amaster), [Linux](../../actions/workflows/linux.yml?query=branch%3Amaster)).

**Comment by SuperVitu64** [comment]
ooh that
i clicked that link, it throws me a dark gray page with the only text being "Not Found"

**Comment by thepwrtank18** [comment]
Windows: https://github.com/UMSKT/UMSKT/actions/workflows/windows.yml?query=branch%3Amaster
Linux: https://github.com/UMSKT/UMSKT/actions/workflows/linux.yml?query=branch%3Amaster

**Comment by SuperVitu64** [comment]
I downloaded it and extracted it, but now it says keys.json isn't in the same directory, even though it is

**Comment by WitherOrNot** [comment]
open a command prompt/terminal and do `cd <Directory where extracted>`, then try running again

**Comment by thepwrtank18** [comment]
Run umskt.exe (or xpkey.exe) through cmd, and make sure your current directory has keys.json in it.

**Comment by SuperVitu64** [comment]
It runs, i give it the telephone key, i type the output but Windows claims i typed it wrong

**Comment by WitherOrNot** [comment]
what version of windows xp are you using?

**Comment by SuperVitu64** [comment]
home edition rtm

**Comment by thepwrtank18** [comment]
Send a screenshot of both umskt and the activation screen.

**Comment by SuperVitu64** [comment]
![image](https://github.com/UMSKT/UMSKT/assets/95242619/d299a453-ca75-4f62-a1af-0e1f40b735c8)

**Comment by WitherOrNot** [comment]
please try this
`140141-431096-233191-141805-592971-881212-405622`

**Comment by WitherOrNot** [comment]
RTM editions have a known bug in confirmation ID generation, we are working on fixing it at the moment

**Comment by SuperVitu64** [comment]
Thanks a lot, it activated! I hope this ID generation bug in RTM versions gets fixed soon too
