### ISSUE TITLE
Stuff I'm working on for this project

### ISSUE THREAD

**Issue by techguy16** [UMSKT/UMSKT#47]
Hi UMSKT team, 
I am working on a few things for this project, which you may be interested in:
- macOS and FreeBSD support (see [here](https://github.com/techguy16/UMSKT))
- Python bridge to UMSKT
- A website for UMSKT

Comment if you are interested.

**Comment by Neo-Desktop** [comment]
macOS should be building just fine, not sure about FreeBSD
I would love to see the changes necessary for them brought into this repo

**Comment by WitherOrNot** [comment]
From what I see in the fork, FreeBSD builds just fine as well. Not sure how it runs though, we will need to actually test in a VM.

As for the python bridge and website, those sound great! Feel free to join the Zulip chat if you'd like to keep us informed on these, it's where we generally discuss this project.

**Comment by techguy16** [comment]
I added a test to the Action which seems to run fine on both macOS and FreeBSD. It's not much hard work, just some changes to CMakeLists.txt, cli.cpp (deprecated function), and add macos.yml and freebsd.yml. 

For the website and the python bridge, I will join the Zulip chat (eventually...)  to discuss these. I will send you a working version soon for both of them. Just respond here for what things you want me to put on there.

**Comment by WitherOrNot** [comment]
For the Python version, my main recommendation is that the modules follow the namespace organization of libumskt. For instance, `umskit.pidgen3.bink2002.verify` interfaces with `PIDGEN3::BINK2002::Verify`.

**Comment by techguy16** [comment]
No it uses the C++ as a backend, with the python code acting as a frontend.

**Comment by techguy16** [comment]
If you wanted to know, I have just got the DOS DJGPP build working.

**Comment by Neo-Desktop** [comment]
the DJGPP build does work for the most part, with two caveats:

* a `noise.sys` or similar randomness driver is necessary
* the DOS Extender required for any djgpp application to function

this isn't documented anywhere, but it needs to be

**Comment by techguy16** [comment]
It's a shame we can't just compile for DOS directly.

**Comment by Neo-Desktop** [comment]
not with openssl, we're working on alternatives at this point

**Comment by techguy16** [comment]
Well, I'm looking into GCC for DOS ports, and HOPEFULLY I can get one working so UMSKT can compile.

Also, as I am working on a website, what pages do you want (other than the homepage and downloads)?

**Comment by Neo-Desktop** [comment]
Ideally the website will also have the emscripten build of umskt

**Comment by techguy16** [comment]
Which one is that?

**Comment by Neo-Desktop** [comment]
it still needs to be made, you should seriously consider joining the zulip chat for this

**Comment by techguy16** [comment]
Ok then I will now.

**Comment by techguy16** [comment]
[techguy16/umsktpy](https://github.com/techguy16/umsktpy/)
My Python bridge.

**Comment by techguy16** [comment]
Closing as completed as they've been completed and released.
