### ISSUE TITLE
Build steps for windows

### ISSUE THREAD

**Issue by DevMichaelSabo** [UMSKT/UMSKT#53]
Hello together
Can the tool only be created under linux??

I installed 
- cmake-3.27.1-windows-x86_64.msi
- make-3.81.exe
- win32openssl-3_0_10.exe
- Visual Studio 2019

My build steps:
- cd build
- cmake ..
- make

But the last step failed with:
makefile:34: *** missing separator.  Schluss.

Line 34 in the generated makefile is:
32: !IF "$(OS)" == "Windows_NT"
33: NULL=
34: !ELSE
35: NULL=nul
36: !ENDIF

Can someone help me?

Thanks

PS: Much easier would be to provide a binary to download here. ;)

**Comment by Neo-Desktop** [comment]
for windows you use cmake provided by visual studio alond with msbuild - check the windows docker file for more information

**Comment by WitherOrNot** [comment]
Issue is stale, closing.
