### ISSUE TITLE
Centralized chat

### ISSUE THREAD

**Issue by CONIGUERO** [UMSKT/UMSKT#6]
As this repository's issues are becoming cluttered with different unorganized messages, I decided to create a dedicated Zulip chat organization for the whole topic.

https://mspid.zulipchat.com

I made 2 channels, one for pidgen and another for the confirmation id system

I chose Zulip because of its openness and excellent topics model: https://zulip.com/help/streams-and-topics

**Comment by Endermanch** [comment]
Great idea! What about Discord though? I think it would be easier to use that, as many have it, even though it's a privacy strainer.

**Comment by CONIGUERO** [comment]
> Great idea! What about Discord though? I think it would be easier to use that, as many have it, even though it's a privacy strainer.

I'm hesitant to use Discord because of the ToS implications. While what we're doing is arguably not damaging to MS or breaking any laws, Discord is known to be very trigger-happy with bans, and one server ToS ban could nuke your whole account.

**Comment by Endermanch** [comment]
> > Great idea! What about Discord though? I think it would be easier to use that, as many have it, even though it's a privacy strainer.
> 
> I'm hesitant to use Discord because of the ToS implications. While what we're doing is arguably not damaging to MS or breaking any laws, Discord is known to be very trigger-happy with bans, and one server ToS ban could nuke your whole account.

Well, I am discussing the entire process with my followers and friends on my semi-public Discord. Still not ToS'ed, lol.
You're kind of right, but as long as there's no arse to report us, we should be good.

**Comment by Neo-Desktop** [comment]
It seems that its also invitation based - we should figure that out as well

For now I've parked myself in #mspid on libera

**Comment by CONIGUERO** [comment]
> It seems that its also invitation based - we should figure that out as well
> 
> For now I've parked myself in #mspid on libera

I can set it to public too! So anyone with the name of the organization can see all the chats and register if they want to

**Comment by Neo-Desktop** [comment]
For sure - I'm also inclined to invite you @CONIGUERO  and @Endermanch as collaborators on this repository if interested I definitely want to spread the love where possible

**Comment by Endermanch** [comment]
> For sure - I'm also inclined to invite you @CONIGUERO and @Endermanch as collaborators on this repository if interested I definitely want to spread the love where possible

Sure, I'm down. As for the chat, please send me the invitation link once you pick the best platform for this case. Would be cool if it were a Discord server, but I understand many respect their own privacy and choose other platforms instead.

**Comment by CONIGUERO** [comment]
> > For sure - I'm also inclined to invite you @CONIGUERO and @Endermanch as collaborators on this repository if interested I definitely want to spread the love where possible
> 
> Sure, I'm down. As for the chat, please send me the invitation link once you pick the best platform for this case. Would be cool if it were a Discord server, but I understand many respect their own privacy and choose other platforms instead.

Thank you!! I don't know how I could help with the coding as I'm no cpp expert, but I'll help on whatever I can!

**Comment by CONIGUERO** [comment]
@Endermanch I also wouldn't mind an invite to your Discord!

**Comment by Endermanch** [comment]
> @Endermanch I also wouldn't mind an invite to your Discord!

The invite link is https://discord.gg/endermanch

It's a paywalled server, but I let anyone I know is mature in. You have to tell me your nick#discrim so I manually approve you. Anyone doing research with us is welcome, btw.

GitHub issue feels like a wrong place to discuss this, but since we're talking about it, I guess it's fine.

**Comment by CONIGUERO** [comment]
> > @Endermanch I also wouldn't mind an invite to your Discord!
> 
> The invite link is https://discord.gg/endermanch
> 
> It's a paywalled server, but I let anyone I know is mature in. You have to tell me your nick#discrim so I manually approve you. Anyone doing research with us is welcome, btw.
> 
> GitHub issue feels like a wrong place to discuss this, but since we're talking about it, I guess it's fine.

Sure. My discord is `thatsadeadtable#3471`

**Comment by Neo-Desktop** [comment]
@Endermanch I went ahead and sent you an email regarding my Discord username

**Comment by smartphonecomputerundmehr** [comment]
> > @Endermanch I also wouldn't mind an invite to your Discord!
> 
> The invite link is https://discord.gg/endermanch
> 
> It's a paywalled server, but I let anyone I know is mature in. You have to tell me your nick#discrim so I manually approve you. Anyone doing research with us is welcome, btw.
> 
> GitHub issue feels like a wrong place to discuss this, but since we're talking about it, I guess it's fine.

my discord name is thisisjustatest#7402

**Comment by Throwaway1453** [comment]
@Endermanch I'd like to join too if possible. My nick is `ExplicitDust#1161` on discord. Thanks in advance!

**Comment by thepwrtank18** [comment]
Discord is TheTank20#0894.

**Comment by Neo-Desktop** [comment]
At this point I'm closing this thread to comments until a better solution is found

**Comment by CONIGUERO** [comment]
@Neo-Desktop @Endermanch What just happened?

**Comment by Endermanch** [comment]
Well, my Discord was just termed. Friend me: __andrew#1093

**Comment by WitherOrNot** [comment]
Dang, was it cause of DMCA?

**Comment by CONIGUERO** [comment]
# **https://umskt.zulipchat.com**

**THE OFFICIAL CHAT IS NOW HERE**

**Comment by WitherOrNot** [comment]
says i need an invite...

**Comment by CONIGUERO** [comment]
> says i need an invite...

Fixed!
