### ISSUE TITLE
Simple 4 steps, not so simple.

### ISSUE THREAD

**Issue by beyerch** [UMSKT/UMSKT#60]
I have no idea what I'm doing wrong, but when I try to follow the README steps, I'm having zero luck with this. 

The issue is with the "download" step which takes you to the Actions tab.  I've looked all over this page; however, all I see are the Action steps history from apparently other executions of this action; however, I can find no way to actually trigger this action.  Googling seems to indicate there should be a button to run it, but no such button exists.  

I have a Github account and am logged in.   

Can someone clarify what should happen on this screen or perhaps provide some additional guidance?

**Comment by pottzman** [comment]
Yes.
1. Click on "Actions"
2. In the Left Click the build you want (linux, windows etc"
3. scroll down to find a workflow run with a green tick (signifies a successful build) and click the hyperlink.
4. go to the bottom where it says artifacts and click on the "name" download link. you may require the openssl package on you pc to run the program

**Comment by thepwrtank18** [comment]
To download OpenSSL, click here and use the right version: https://slproweb.com/products/Win32OpenSSL.html

**Comment by beyerch** [comment]
> To download OpenSSL, click here and use the right version (if you're on Windows): https://slproweb.com/products/Win32OpenSSL.html

I already have OpenSSL, but this is also good info for others, thanks!

**Comment by beyerch** [comment]
> Yes.
> 
> 1. Click on "Actions"
> 2. In the Left Click the build you want (linux, windows etc)
> 3. scroll down to find a workflow run with a green tick (signifies a successful build) and click the hyperlink.
> 4. go to the bottom where it says artifacts and click on the "name" download link. you may require the openssl package on you pc to run the program

*THIS* is what I needed, thanks!

Ironically, I did start to do this, but where I messed up is when I went into a successful action, I then click on the Job link at the top of the page which took me into the step by step output.  I saw some references to it uploading files, but didn't see any sort of link.  

I didn't even notice the separate section on the first page with the artifact attachments!  OOPS!

Thanks for the additional detail, this really helped!
