### ISSUE TITLE
Plus! Digital Media Edition not supported

### ISSUE THREAD

**Issue by Jujan** [UMSKT/UMSKT#76]
Hello,
Microsoft Plus! Digital Media Edition is the only Plus! pack requiring activation. Activation servers are obviously dead, but it supports phone activation.
Installation ID of it is not supported by UMSKT.
Looks like a little different format.

I know it is pretty exotic piece of MS software, but analyzing would bring more interesting information to Registration ID generation.

Would it be possible to add support for it?

**Comment by WitherOrNot** [comment]
Plus! Digital Media Edition is currently supported. You can activate it like so:

`umskt -i <Installation ID> -m PLUSDME`

**Comment by thepwrtank18** [comment]
We should definitely work trying to differentiate the product from the Installation ID. Looping over every mode won't work, since iirc OFFICE2K3 gives an invalid confid rather than an error if a Plus! DME instid is used (and vice versa).
