### ISSUE TITLE
List of discontinued Windows Versions with activation

### ISSUE THREAD

**Issue by DotNetTester** [UMSKT/UMSKT#78]
I'll update this list occasionally. There are even older versions of Windows that did have product keys but did not require activation. The activation tool could support them.

Windows XP Home Edition and Professional
Windows XP Professional x64 Edition
Windows Vista Home Basic, Home Premium, Professional and Ultimate
Windows 7 Home Basic, Home Premium, Professional and Ultimate
Windows 8.1 "Basic" and Pro

Windows Server 2003 Standard, Enterprise and Datacenter 32-bit
Windows Server 2003 Standard, Enterprise and Datacenter x64 editions
Windows Server 2008 Standard, Enterprise and Datacenter - 32-bit and 64-bit
Windows Server 2008 R2 Standard, Enterprise and Datacenter
Windows Server 2012 Standard and Datacenter
Windows Server 2012 R2 Standard and Datacenter

**Comment by DotNetTester** [comment]
Windows 7 and Windows Server 2008 R2 were really popular releases and there was/is Extended Security Updates (ESU). Windows 7 got three additional years of security updates and Windows Server 2008 R2 will be getting four additional years of security updates that ends in January. I do wonder if this is another possible target for this activation tool. I'd wait on supporting Windows Server 2008 R2 until after January.

**Comment by DotNetTester** [comment]
Windows 8.1 support was dropped in January 2023 and Windows Server 2012 R2 support was dropped in October 2023.

**Comment by techguy16** [comment]
@DotNetTester we are working on PKEY2005 product key generation. Most of the products you list here use that style, so eventually UMSKT or another tool of some sort will support generating this sort of key. 

Random Tip: Edit your original post just so it doesn't get cluttered.

**Comment by Neo-Desktop** [comment]
vista+ needs further research and development.
XP/2K3 are currently supported
