### ISSUE TITLE
Compiling on debian 12 not working

### ISSUE THREAD

**Issue by arminmoradi96** [UMSKT/UMSKT#83]
Hello,

i want to compile this great project.
I using debian 12 and i have installed the three packages wich are listed in the readme.
Heere i post the SSH screen, where the error messages are displayed:

I run the command cmake ..

-- [UMSKT] Requesting static version of OpenSSL
CMake Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.25/Modules/FindOpenSSL.cmake:613 (find_package_handle_standard_args)
  CMakeLists.txt:102 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/home/dev/UMSKT/build/CMakeFiles/CMakeOutput.log".

I attach the log file, what i make wrong?
Wich Linux distribution do you use and wich version?
Can i compile it on windows?

Regards
Armin
[CMakeOutput.log](https://github.com/UMSKT/UMSKT/files/14318305/CMakeOutput.log)

**Comment by Neo-Desktop** [comment]
debian needs libssl-dev and pkg-config
you should be able to compile this on windows using cmake

**Comment by arminmoradi96** [comment]
Thank you, that helped me.
What i find shoult in the readme:
If you use debian, you should install the folowing extra packages:
apt-get install libssl-dev pkg-config zlib1g-dev -y

Now i try compile it on windows, when i need help, i will open a new issue.

Regards
arminomoradio96
