### ISSUE TITLE
XP home edition key generation

### ISSUE THREAD

**Issue by arminmoradi96** [UMSKT/UMSKT#84]
Hello,

i have my first Windows XP Home edition Service Pack 2 CD in german language. I have tryed to install it with a generated key, but setup does'nt accept.
I have read in the issue #4 that the pid 640, volume license generation is used in default.
Can you list the possible pid's and for wich windows XP editions they are?
How can i seh, wich license is used, the name of the cd drive is, when i insert the cd is: VX2HOEM_DE
Please help me.

Regards
arminmoradi96

**Comment by arminmoradi96** [comment]
I send you my setupp.ini, there i have used the 063 number.
COmmand: ./umstk -c 063
The program displays a key, but the installation program does'not accept the key.
I have try three times.
I attach my setupp.ini.

Regards
Armin
[SETUPP.txt](https://github.com/UMSKT/UMSKT/files/14323603/SETUPP.txt)

**Comment by thepwrtank18** [comment]
Try `./umskt -c 143 -b 2B`.

**Comment by arminmoradi96** [comment]
Year, now it works.
Can you explain me the parameters and the numbers, i coult not seh it in my setupp.ini file. How i can calculate the number and the B parameter?

Armin

**Comment by Neo-Desktop** [comment]
the correct Channel ID and BINK ID can only be obtained from disassembling `pidgen.dll` and also looking at it's resources.

You would need a database to lookup to get those values from a given MS Product Code as seen in `setupp.ini`

**Comment by arminmoradi96** [comment]
Ok, thank you.
Wich tool do you use to disaasembling the DLL file?

**Comment by Neo-Desktop** [comment]
ghidra but, but teaching people how to reverse engineer is beyond the scope of this project
