### ISSUE TITLE
error compiling on windows

### ISSUE THREAD

**Issue by arminmoradi96** [UMSKT/UMSKT#85]
Hello,

i have tryed to compile this nice project on windows.
I have installed cmake and open ssl.
I open a commandline, go to the build folder and i type make ..
The folowing error message apears:

CMake Error at CMakeLists.txt:22 (PROJECT):
  Running

   'nmake' '-?'

  failed with:

   no such file or directory

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

I don't understoud, what for errors are heere, do i have forgotten to install a program?
I attach the make textfile with the informations.

Regards
arminmoradi
[CMakeCache.txt](https://github.com/UMSKT/UMSKT/files/14322624/CMakeCache.txt)
96

**Comment by Neo-Desktop** [comment]
from the project root directory
`cmake -B build/ && cmake --build build/`
this should work on VS 2019+ in a Visual Studio Command Prompt

**Comment by arminmoradi96** [comment]
I have try it, but, the same error apears.

Armin

**Comment by arminmoradi96** [comment]
Ok, i have now seen, that c++ components was not installed.
now, it says, that the module openssl librais coult not found.
What i make wrong?

Armin

**Comment by Neo-Desktop** [comment]
you need to install the openssl development libraries.. quite literally as it says..
