### ISSUE TITLE
Windows XP professional Servicepack 3 CD Key generation

### ISSUE THREAD

**Issue by arminmoradi96** [UMSKT/UMSKT#86]
i have found in my shelf a windows XP professional Service Pack 3 CD in German.
I don't understoud that thing with the Bink and PID'S. Should i send you the setupp.ini and the pidgen.dll files?

Regards
Armin

**Comment by techguy16** [comment]
Hi @arminmoradi96,
The command you need to generate keys for that version is either `umskt -b 2C -c 335` or `umskt -b 2D -c 335`.

**Comment by arminmoradi96** [comment]
Thank you, you helped me.

Regards
Armin
