### ISSUE TITLE
XP pro SP2 Key generation

### ISSUE THREAD

**Issue by arminmoradi96** [UMSKT/UMSKT#87]
### 
in issue #86 you have sugested me, that i should try the folowing command:

umskt -b 2C -c 335
or
umskt -b 2D -c 335
I have tryed both commands for XP pro SP2, 2C was the key correct, but, the activation window opens and when i press alt+F4, it logs me off.
Do you have an sugestion?

Regards
Armin

**Comment by techguy16** [comment]
On non-VLK versions of XP, you have to also either activate via telephone or internet. As you cannot activate via internet now, use the telephone option. Once you get the code that you provide over the phone (usually), run the command `umskt -i <code>` and type in the output like you usually would if you activated it via telephone.

**Comment by arminmoradi96** [comment]
Ok, tahnk you.
With XP pro SP3, the activation window don't open, it says, that i have 30 days remaining to activate.
With XP pro, SP2, the activation window directly after the installation, the problem is, i am blind and i can't read the window, before i have installed a screen reader.
Why it works with XP pro SP3 and not with XP pro SP2?

Regards
Armin

**Comment by Neo-Desktop** [comment]
the behavior described here is from WPA detecting a channel ID that is not in the allow list. Further diagnosis would require an archive.org link to the disc image used (we are specifically looking for values in dpc.dll)

**Comment by thepwrtank18** [comment]
Any link works fine, it just has to go to the ISO file.

**Comment by arminmoradi96** [comment]
Hello,

sorry for the late replay.
Heere is the Link to the iso image: https://archive.org/download/WindowsXPProfessionalSP2German/DE_WINDOWS_XP_PROFESSIONAL_WITH_SP2.ISO

I will try to generate other keys.

Regards
Armin

**Comment by Neo-Desktop** [comment]
`SETUPP.INI` shows that this is a `Retail` version of XP.
`PIDGEN.DLL` shows `BINKs` `2C` and `2D` are available, `Retail` copies use the 2nd `BINK`.
`DPCDLL.DLL` shows that for `BINK 2D`, `Channel ID 120` should work as intended

Please try `umskt -b 2D -c 120`

**Comment by arminmoradi96** [comment]
Ok, i will try it after my work.
A sugestion:
A Website, where i upload the .dll files and the setupp.ini file, they will show me, wich id i should i use.

I am a hobby programmer and i have not mouch skills.
Thank you for your help, i will let you know, when it worked.

Armin

**Comment by Neo-Desktop** [comment]
there has been discussion in the development channels about this

it may be built into umskt in the future

**Comment by arminmoradi96** [comment]
Ok, it don't work.
I have tryed as channel 2C and 2D and the 120.
With 2D, it says, that the product key is wrong.
With 2D, it accepts during the installation the key, but after it forces me to activate and gives not the chance for the 30 day perriot.
I have use that tool: https://mskt.surge.sh/

Armin

**Comment by arminmoradi96** [comment]
I have ordered a XP pro SP2 OEM CD, should i upload the setupp.ini, pidgen.dll and the other dll file you sayd?, that you can look, wich bink and wich channel i should use?

Thank you for your help
Armin

**Comment by arminmoradi96** [comment]
I upload the files, can you say me, wich parameters i should i use for the key generation?

Armin
[DPC.txt](https://github.com/UMSKT/UMSKT/files/14472344/DPC.txt)
[PIDGEN.txt](https://github.com/UMSKT/UMSKT/files/14472345/PIDGEN.txt)
[SETUPP.txt](https://github.com/UMSKT/UMSKT/files/14472346/SETUPP.txt)

You must rename the file types to setupp.ini, pidgen.dll and to DPC.dll

**Comment by pottzman** [comment]
I used this command to produce a valid key for Windows XP SP2 OEM

umskt -p WINXP -f PRO -O -c 120

where
-p WINXP is for Windows XP
-f PRO is for Professional
-O is for an OEM Product Key
-c 120 is to produce a product key with a Channel ID of 120

**Comment by arminmoradi96** [comment]
When i run the command it says, parse error.


Armin

**Comment by Wannabe99** [comment]
-f PRO??? 
-O ???
-p is only for Office???
Looking through the source code those command line parameters can't be right, @pottzman?

**Comment by thepwrtank18** [comment]
> I used this command to produce a valid key for Windows XP SP2 OEM
> 
> umskt -p WINXP -f PRO -O -c 120
> 
> where -p WINXP is for Windows XP -f PRO is for Professional -O is for an OEM Product Key -c 120 is to produce a product key with a Channel ID of 120

This only works in the Neo-Desktop refactored version, which isn't in the main branch yet.

**Comment by arminmoradi96** [comment]
Ok i don't know exactly, how i have done that, it works now. Thank you and have a nice rest soun day and a good week.

Armin
