### ISSUE TITLE
Office 2007 Enterprise activation not working (no output)

### ISSUE THREAD

**Issue by jonaskohl** [UMSKT/UMSKT#90]
I'm trying to activate Office 2007 Enterprise (DE) on Windows Vista Ultimate using the key `FQT9W-2Y8M2-X9W9D-3FJ29-HJ8VM` (generated by UMSKT as well). When issuing the following command:

```
umskt.exe -c 864 -p OFFICE2K7 -f PRO -i 065795-710280-096543-513302-537511-539171-299093-205161-559725 -P 81599-864-7510697-65628
```

I get no output. When adding a `-v`, the output is as follows:

```
Enabling verbose option

Loading internal keys file
Loaded internal keys file successfully

Selecting product: OFFICE2K7
Selecting flavour: PRO

--------------------------------------------------------------------------------

Loaded the following hyperelliptic curve parameters: activation[OFFICE]
--------------------------------------------------------------------------------

   name: Office XP/2003/2007
version: 4
     Fp: 103099955908255721
    F[]: [0, 64728167274549202, 4488766805843809,
          70698430483539942, 64728167274549202, 1]
    INV: 14515793565989355059134123881456714
   mqnr: 3
      k: 10294349293510589382098112327865153
    IID: 1513142771

```

The confirmation ID is correct (I triple-checked) and the product ID is also correct (I copied it out of the registry). The channel ID is taken from another, known working product key (but activation for that key failed with the same symptoms as described here).

**Comment by thepwrtank18** [comment]
![image](https://github.com/UMSKT/UMSKT/assets/57580668/a1828908-294f-4d79-ac63-5891886612c5)

**Comment by Neo-Desktop** [comment]
Thanks for that @thepwrtank18 

@jonaskohl, please use code from the current master branch for generating activation IDs, the refactor branch is currently broken while I work on porting the activation implementation from the current mess to using a (semi-standardized) library

**Comment by jonaskohl** [comment]
Building from source and using that worked perfectly fine, thank you! (I used macOS 14.4.1 ARM64 using CMake 3.28.1 and Clang 15.0.0 (clang-1500.3.9.4))
